"""Add steps to exception

Revision ID: 288df372ada3
Revises: add_comment_enhancements
Create Date: 2025-12-14 13:31:47.488220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288df372ada3'
down_revision: Union[str, Sequence[str], None] = 'add_comment_enhancements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exceptions', sa.Column('steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'aid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_person_name_project'), 'people', ['name', 'project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('exceptions', 'steps')
    # ### end Alembic commands ###
