"""Convert UseCase exceptions to JSON

Revision ID: 2b5fd9573d1b
Revises: 288df372ada3
Create Date: 2025-12-14 13:43:40.431260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5fd9573d1b'
down_revision: Union[str, Sequence[str], None] = '288df372ada3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_cases', sa.Column('exceptions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'aid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('use_cases', 'exceptions')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_person_name_project'), 'people', ['name', 'project_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
