"""Add tags to sites

Revision ID: 30f7f300d25d
Revises: 72a263921074
Create Date: 2025-12-09 22:33:40.180592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f7f300d25d'
down_revision: Union[str, Sequence[str], None] = '72a263921074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # op.create_foreign_key(None, 'people', 'projects', ['project_id'], ['id'])
    op.add_column('sites', sa.Column('tags', sa.String(), nullable=True))
    # op.alter_column('users', 'aid',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'aid',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.drop_column('sites', 'tags')
    # op.drop_constraint(None, 'people', type_='foreignkey')
    op.alter_column('documents', 'content_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
