"""Add EARS fields to requirements

Revision ID: 6026e0885dc4
Revises: 98ed423f8510
Create Date: 2025-11-24 20:30:01.094430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6026e0885dc4'
down_revision: Union[str, Sequence[str], None] = '98ed423f8510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('ears_trigger', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('ears_state', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('ears_condition', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('ears_feature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'ears_feature')
    op.drop_column('requirements', 'ears_condition')
    op.drop_column('requirements', 'ears_state')
    op.drop_column('requirements', 'ears_trigger')
    # ### end Alembic commands ###
