"""Add content to diagrams

Revision ID: 72a263921074
Revises: 8a6a44960292
Create Date: 2025-12-09 16:01:01.443752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a263921074'
down_revision: Union[str, Sequence[str], None] = '8a6a44960292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('content', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'content')
    # ### end Alembic commands ###
