"""add_project_id_isolation

Revision ID: e8967371929b
Revises: fc3e4eb46115
Create Date: 2026-01-22 16:39:29.905187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8967371929b'
down_revision: Union[str, Sequence[str], None] = 'fc3e4eb46115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'areas', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('diagram_components_component_id_fkey'), 'diagram_components', type_='foreignkey')
    op.create_foreign_key(None, 'diagram_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('diagram_edges_target_id_fkey'), 'diagram_edges', type_='foreignkey')
    op.drop_constraint(op.f('diagram_edges_source_id_fkey'), 'diagram_edges', type_='foreignkey')
    op.create_foreign_key(None, 'diagram_edges', 'components', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diagram_edges', 'components', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('need_components_component_id_fkey'), 'need_components', type_='foreignkey')
    op.create_foreign_key(None, 'need_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('need_sites_site_id_fkey'), 'need_sites', type_='foreignkey')
    op.create_foreign_key(None, 'need_sites', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_person_name_project'), 'people', type_='unique')
    op.create_foreign_key(None, 'people', 'projects', ['project_id'], ['id'])
    op.add_column('sites', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sites', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('use_case_exceptions_exception_id_fkey'), 'use_case_exceptions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_exceptions', 'exceptions', ['exception_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_postconditions_postcondition_id_fkey'), 'use_case_postconditions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_postconditions', 'postconditions', ['postcondition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_preconditions_precondition_id_fkey'), 'use_case_preconditions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_preconditions', 'preconditions', ['precondition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_stakeholders_person_id_fkey'), 'use_case_stakeholders', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_stakeholders', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'use_case_stakeholders', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_stakeholders_person_id_fkey'), 'use_case_stakeholders', 'people', ['person_id'], ['id'])
    op.drop_constraint(None, 'use_case_preconditions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_preconditions_precondition_id_fkey'), 'use_case_preconditions', 'preconditions', ['precondition_id'], ['id'])
    op.drop_constraint(None, 'use_case_postconditions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_postconditions_postcondition_id_fkey'), 'use_case_postconditions', 'postconditions', ['postcondition_id'], ['id'])
    op.drop_constraint(None, 'use_case_exceptions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_exceptions_exception_id_fkey'), 'use_case_exceptions', 'exceptions', ['exception_id'], ['id'])
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'project_id')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_person_name_project'), 'people', ['name', 'project_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'need_sites', type_='foreignkey')
    op.create_foreign_key(op.f('need_sites_site_id_fkey'), 'need_sites', 'sites', ['site_id'], ['id'])
    op.drop_constraint(None, 'need_components', type_='foreignkey')
    op.create_foreign_key(op.f('need_components_component_id_fkey'), 'need_components', 'components', ['component_id'], ['id'])
    op.drop_constraint(None, 'diagram_edges', type_='foreignkey')
    op.drop_constraint(None, 'diagram_edges', type_='foreignkey')
    op.create_foreign_key(op.f('diagram_edges_source_id_fkey'), 'diagram_edges', 'components', ['source_id'], ['id'])
    op.create_foreign_key(op.f('diagram_edges_target_id_fkey'), 'diagram_edges', 'components', ['target_id'], ['id'])
    op.drop_constraint(None, 'diagram_components', type_='foreignkey')
    op.create_foreign_key(op.f('diagram_components_component_id_fkey'), 'diagram_components', 'components', ['component_id'], ['id'])
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'project_id')
    # ### end Alembic commands ###
