"""Sync user model schema and security fields

Revision ID: fc3e4eb46115
Revises: d5fb701d550d
Create Date: 2026-01-06 05:53:59.629302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3e4eb46115'
down_revision: Union[str, Sequence[str], None] = 'd5fb701d550d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diagram_components_component_id_fkey'), 'diagram_components', type_='foreignkey')
    op.create_foreign_key(None, 'diagram_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('diagram_edges_target_id_fkey'), 'diagram_edges', type_='foreignkey')
    op.drop_constraint(op.f('diagram_edges_source_id_fkey'), 'diagram_edges', type_='foreignkey')
    op.create_foreign_key(None, 'diagram_edges', 'components', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diagram_edges', 'components', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('need_components_component_id_fkey'), 'need_components', type_='foreignkey')
    op.create_foreign_key(None, 'need_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('need_sites_site_id_fkey'), 'need_sites', type_='foreignkey')
    op.create_foreign_key(None, 'need_sites', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_person_name_project'), 'people', type_='unique')
    op.create_foreign_key(None, 'people', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('use_case_exceptions_exception_id_fkey'), 'use_case_exceptions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_exceptions', 'exceptions', ['exception_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_postconditions_postcondition_id_fkey'), 'use_case_postconditions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_postconditions', 'postconditions', ['postcondition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_preconditions_precondition_id_fkey'), 'use_case_preconditions', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_preconditions', 'preconditions', ['precondition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('use_case_stakeholders_person_id_fkey'), 'use_case_stakeholders', type_='foreignkey')
    op.create_foreign_key(None, 'use_case_stakeholders', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    # User Table Schema Fixes
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('password_expired', sa.Boolean(), nullable=True, server_default='false'))
    
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               postgresql_using='is_active::boolean',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'password_expired')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'use_case_stakeholders', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_stakeholders_person_id_fkey'), 'use_case_stakeholders', 'people', ['person_id'], ['id'])
    op.drop_constraint(None, 'use_case_preconditions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_preconditions_precondition_id_fkey'), 'use_case_preconditions', 'preconditions', ['precondition_id'], ['id'])
    op.drop_constraint(None, 'use_case_postconditions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_postconditions_postcondition_id_fkey'), 'use_case_postconditions', 'postconditions', ['postcondition_id'], ['id'])
    op.drop_constraint(None, 'use_case_exceptions', type_='foreignkey')
    op.create_foreign_key(op.f('use_case_exceptions_exception_id_fkey'), 'use_case_exceptions', 'exceptions', ['exception_id'], ['id'])
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_person_name_project'), 'people', ['name', 'project_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'need_sites', type_='foreignkey')
    op.create_foreign_key(op.f('need_sites_site_id_fkey'), 'need_sites', 'sites', ['site_id'], ['id'])
    op.drop_constraint(None, 'need_components', type_='foreignkey')
    op.create_foreign_key(op.f('need_components_component_id_fkey'), 'need_components', 'components', ['component_id'], ['id'])
    op.drop_constraint(None, 'diagram_edges', type_='foreignkey')
    op.drop_constraint(None, 'diagram_edges', type_='foreignkey')
    op.create_foreign_key(op.f('diagram_edges_source_id_fkey'), 'diagram_edges', 'components', ['source_id'], ['id'])
    op.create_foreign_key(op.f('diagram_edges_target_id_fkey'), 'diagram_edges', 'components', ['target_id'], ['id'])
    op.drop_constraint(None, 'diagram_components', type_='foreignkey')
    op.create_foreign_key(op.f('diagram_components_component_id_fkey'), 'diagram_components', 'components', ['component_id'], ['id'])
    # ### end Alembic commands ###
